spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/JWT
    username: postgres
    password: "@Amin0076"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        database: postgresql